### ISSUE TITLE
titles should overlay images in grid layout

### ISSUE THREAD

**Issue by bridgetkromhout** [mattstratton/castanet#135]
### Expected behavior

For Arrested DevOps, having the most recent ep be a video link makes it confusing and unlikely that people would know to click on the episode title to get to the episode page where there is more content. Instead of a list where everything is an image but the first one which is a video, let's have a grid like @mattstratton showed me in https://www.castanet-theme.com/grey-grid/ - if possible, with the 500x500 images clickable (as described in https://github.com/mattstratton/castanet/issues/134) and the titles overlaid on them as before (since the images were designed assuming that).

### Actual behavior

Currently we lack a grid and have a "hero" video, which I think is misleading.

### Reproduction Steps

Look at the current draft site in https://deploy-preview-297--arrested-devops.netlify.com/

**Comment by mattstratton** [comment]
This seems to be a question for the Arrested DevOps implementation. The use of the grid as an option is a configuration in the `config.toml` of the site which is using this theme, although the enhancement would be to have titles overlaid on the images instead of below them?

**Comment by mattstratton** [comment]
I'm not sure where, but this was fixed at some point. Closing.
