### ISSUE TITLE
[Enhancement] Can disqus comments be made optional?

### ISSUE THREAD

**Issue by thercast** [mattstratton/castanet#136]
I've had great success with using `castanet` for my podcast site (and again thanks for the great updates lately) and I'd like to use it for an internal hugo site at work that will function very similar to my podcast site give or take a few differences.  Since it will be within the firewall we don't have a desire to use disqus for episode comments.  I couldn't find any language around making disqus comments optional, but would there be a way to disable it in the site config?

**Comment by mattstratton** [comment]
This seems quite reasonable! I'll start working on it soon.
