### ISSUE TITLE
[Bug] README.md Installation step should describe required Menu.Main config.toml setting

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#152]
### Expected behavior
Following hugo getting started and castanet installation instructions should result in a basic rendered hugo site. 
### Actual behavior
After following hugo getting started and castanet installation hugo server -D displays an error related to Site.Menus.
### Reproduction Steps
Starting from scratch, follow hugo getting started steps and install the castanet theme. hugo server -D displays an error no rendered website.
### Operating System and Version
n/a
### Web Browser and Version
n/a
### Hugo Version
hugo v.0.36.1 windows/amd64

**Comment by rajeshduggal** [comment]
This fix for this could be just to document adding the menu to the config.toml as a required step in the installation instructions.

**Comment by mattstratton** [comment]
I think I can actually add some code that will check to see if there are any menu elements before trying to display them.
