### ISSUE TITLE
[Bug] iTunes/android/Soundcloud subscribe image icons broken

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#155]
### Expected behavior
Every subscribe button icon should have a unique icon
### Actual behavior
iTunes/android/Soundcloud subscribe image icons broken, others display correctly.
![subscribe_buttons](https://user-images.githubusercontent.com/27322/36936705-be089362-1ed6-11e8-8035-2d682272cca7.JPG)
### Reproduction Steps
Copy *_subsribe variables from exampleSite/config.toml into config.toml so that icons are displayed. Notice the broken icon images.
### Operating System and Version
Windows 7
### Web Browser and Version
Chrome Version 64.0.3282.140 (Official Build) (32-bit)
### Hugo Version
Hugo v0.36.1 windows/amd64

**Comment by mattstratton** [comment]
I suspect (and will try to reproduce) that this came from when I upgraded FontAwesome. I'm going to be doing a deep dive into bugs this week. Thanks for reporting these!

**Comment by rajeshduggal** [comment]
Thanks for the fix!  The buttons looks good on our website now.. https://khabardaarpodcast.com/
