### ISSUE TITLE
Error when no menu items are set in config file

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#165]
Currently, if no menu is set, the theme will error out. Should add a check to ensure there are menu items before trying to display them.

**Comment by thunderrabbit** [comment]
I'd like to have a crack at this.  Where in the code does this check need to happen?

I am asking because I want to add *different* menu items, so I will be happy to mess with menu stuff for a bit.

**Comment by mattstratton** [comment]
The code to fix is here: https://github.com/mattstratton/castanet/blob/master/layouts/partials/header.html#L11

Basically, we need to wrap the whole menu part with a query that does a range of `.Site.Menus.main` and if the count is <1, then it shouldn't execute any of the menu code I think.

**Comment by chrisreddington** [comment]
@mattstratton  - Think it would be something like this.. 

{{ if ge (len .Site.Menus.main) 1 }}
   // Display the menu
{{ end }}

Happy to include it in one of my PRs and test, if useful?

**Comment by chrisreddington** [comment]
Also, I guess this is a bug rather than enhancement :)

**Comment by mattstratton** [comment]
I think this looks like the right test. I would put it in as a separate PR though rather than pushing it with another one, just to keep it cleaner.

**Comment by mattstratton** [comment]
Fixed in #371
