### ISSUE TITLE
[Bug] Apostrophe in episode Description field is rendered as lsquo in RSS index.xml

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#180]
### Expected behavior
Single-quote (apostrophe) in episode description field should build a valid index.xml.
### Actual behavior
Apostrophe in episode description field is rendered as &lsquo which is invalid XML and displays an error in chrome as "Entity 'lsquo' not defined" when visiting the rss url.
See: https://html.spec.whatwg.org/multipage/xhtml.html (entity references for characters in XML documents is unsafe if they are defined in an external file (except for &lt;, &gt;, &amp;, &quot; and &apos;).
See: http://www.drdobbs.com/web-development/elimination-of-text-corruption-in-xml/220300907 (XML parsers recognize only five symbols -- &amp; &quot; &apos; &lt; &gt;. All other valid character entity references (like &mdash; &eacute;) are not recognizable by XML parsers)
### Reproduction Steps
Create an episode md file. Include a single-quote (apostrophe). View the rendered xml and notice the &lsquo. Visit the rendered index.xml url in chrome and see an error message.
### Operating System and Version
Windows 7
### Web Browser and Version
chrome windows 64.0.3282.140
### Hugo Version
v0.36.1 windows/amd64

**Comment by rajeshduggal** [comment]
@mattstratton this is still a problem for us.. every time we publish an episode our rss breaks and I have to remove the apostrophes. Is this a quick fix for you or should I try to dig into the code and try to fix it? Much Appreciated!

**Comment by mattstratton** [comment]
I believe this must be resolved, because we have had episodes of [Arrested DevOps](https://www.arresteddevops.com) recently with apostrophes, and they didn't break :)
