### ISSUE TITLE
[ENHANCEMENT] Add support for blog posts

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#19]
Right now, it basically only works for episodes. But a podcast might have a blog as well, and want to have those posts.

At the minimum, need a section for blogs, including (possibly) their own RSS. Although I think that most folks would subscribe to just the main one.

Also need a template for blog posts.

Should possibly have a toggle in the `config.toml` to choose whether or not blog posts should be included on the home page along with episodes. Displaying blog posts interspersed with episodes will require some more logic on the part of the display.

**Comment by mattstratton** [comment]
I imagine this would take a similar implementation to how it is done in [devopsdays/devopsdays-theme](https://github.com/devopsdays/devopsdays-theme) which provides a separate, specific RSS for the blog posts themselves.

Definitely open for suggestions on whether or not blog posts should be displayed inline with the episodes on the homepage.

**Comment by thercast** [comment]
I'm planning on creating non-episode posts for my podcast site so this feature is fresh in my mind.  Personally I would not need them to be on the main page since they won't be what I consider the main content. I do like the idea of a separate rss feed although it is a nice-to-have and not a must.  It seems then the major item would be a template.   I'll take a look at the devopsdays theme to see how you managed that piece.

**Comment by chrisreddington** [comment]
@rpodcast how did you get on with this? It's something i'm considering, as I want to collapse my personal website/blog into a blog on my podcast site, and have them all in one place.

@mattstratton - I thought in another GitHub issue that this may be possible already, but undocumented. Wondered if I'm making that up or that rings a bell? :)

**Comment by mattstratton** [comment]
> I thought in another GitHub issue that this may be possible already, but undocumented. Wondered if I'm making that up or that rings a bell? :)

I don't recall writing anything about it, but in theory I think you could get there, but you'd have to add some templates (you could do that in your own site outside the theme). You'd have to create a section called "blog" or something and create the templates for it (and for its feed). 

it would definitely be cleaner to do it properly in the theme; I'll bump this up in priority as I don't think it would be too very hard to do (if you want to see the things to do in general, take a look at [devopsdays/devopsdays-web](https://github.com/devopsdays/devopsdays-web), specifically the `blog` and `section` directories inside its theme).

**Comment by mattstratton** [comment]
Thinking about this a little bit - I think that in addition to creating the associated templates (and some documentation on how to set it up, i.e., where the blog posts go, etc) we probably want to add a) an example menu item for the blog to `exampleSite` as well as also a new "subscribe to blog" button in the various places (like the jumbotron, etc). 

also, since I just added a thing that links to the episode RSS in the `<HEAD>` I need to do a little research on if we should be adding the blog RSS in there too.

**Comment by mattstratton** [comment]
okay so here's the trick for that.

if it's a blog-related page (either a post or the list of blog posts) then `  <link rel="alternate" type="application/rss+xml" href="rss-feed">` should be set to the blog's rss.

if not, it should default to the episode feed.

**Comment by mattstratton** [comment]
okay I have the framework for this, but the trick is the look and feel. I suspect we probably want to mirror `row` and `grid` and use similar layouts for the blog listings. I'll see if I can hack something like that quickly and get a draft PR pushed up today.

**Comment by chrisreddington** [comment]
Also worth calling out the changes in #324 which will be merged into #310
