### ISSUE TITLE
[Bug?] Error when creating any new episode file

### ISSUE THREAD

**Issue by ryanstraight** [mattstratton/castanet#194]
Am building through Blogdown in RStudio.

### Expected behavior
New content (episode) should be created and populated with metadata.

### Actual behavior
File created but errors pop up while using the live server preview:

```
Building sites â€¦ ERROR 2018/08/05 18:09:22 Error while rendering "home" in "": template: index.html:5:8: executing "main" at <partial "grid.html" ...>: error calling partial: template: partials/grid.html:16:55: executing "partials/grid.html" at <absURL>: wrong number of args for absURL: want 1 got 0
Building sites â€¦ ERROR 2018/08/05 18:09:22 Error while rendering "home" in "": template: index.html:5:8: executing "main" at <partial "grid.html" ...>: error calling partial: template: partials/grid.html:16:55: executing "partials/grid.html" at <absURL>: wrong number of args for absURL: want 1 got 0
The system cannot find the path specified.
<simpleError in shell(cmd, mustWork = TRUE, intern = intern): '"C:\Users\User\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" -t castanet' execution failed with error code 1>
```

### Reproduction Steps
Doesn't matter if file is created via command line or created as a new file or a copy of another file. Once the file is deleted, the live preview resumes building just fine. 

### Versions
R: 3.5.1
RStudio: 1.1.456
Blogdown: 0.8.3 
Hugo: 0.46
Castanet: 0.10.0

**Comment by mattstratton** [comment]
I don't have access to RStudio, so I don't know how to reproduce this.
