### ISSUE TITLE
Castanet Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [mattstratton/castanet#197]
Hello @mattstratton 

Currently I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

It has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo on the Hugo website [Castanet](https://themes.gohugo.io/castanet/) has third party tracking enabled.

```
     \castanet\exampleSite\config.toml:
        googleAnalytics = "UA-100789009-1"
        disqusShortname = "arresteddevops"
```

To fix this issue please leave the above parameters blank i.e.

```
        googleAnalytics = ""
        disqusShortname = ""
```

Once you look into this please let me know.

Thank you!

**Comment by mattstratton** [comment]
Whoops! I’ll take care of this shortly!

**Comment by mattstratton** [comment]
@onedrawingperday Just fixed this! Thanks for the heads up!

**Comment by onedrawingperday** [comment]
Thanks for the fix @mattstratton 👍
