### ISSUE TITLE
[Bug] Pagination is broken on mobile and needs general improvement.

### ISSUE THREAD

**Issue by vichudson1** [mattstratton/castanet#202]
### Expected behavior
There should be a next page button and first and last page buttons should only appear when relevant.
### Actual behavior
The first and last page buttons are always visible and there is no next page button ever. This is not as critical on desktop where we have page number buttons, but is bad on mobile where the page number buttons disappear. The site visitor can only go to the last page and then work their way back through the pages.
### Reproduction Steps
Visit a castanet themed hugo site on mobile device
### Operating System and Version
Any
### Web Browser and Version
Mobile devices or narrow browser windows
### Hugo Version
Hugo Static Site Generator v0.54.0/extended darwin/amd64

**Comment by vichudson1** [comment]
I've submitted [PR-201](https://github.com/mattstratton/castanet/pull/201) with fixes for this.

**Comment by mattstratton** [comment]
Fixed in https://github.com/mattstratton/castanet/pull/201
