### ISSUE TITLE
Per-show Tweet link leads to wrong pre-filled text in tweet

### ISSUE THREAD

**Issue by alexmurray** [mattstratton/castanet#203]
For example, using the demo site at https://sample-castanet.netlify.com/sept/ 

### Expected behavior
Clicking "Tweet" button on an episode's page results in a pre-filled tweet with

    Back to School via @arresteddevops

### Actual behavior
Clicking "Tweet" button on an episode's page results in a pre-filled tweet with 

    Back to School https://twitter.com/share?&text=Back%20to%20School&via=arresteddevops via @arresteddevops

### Reproduction Steps
Click Tweet button link on above page or any other page using castanet

### Operating System and Version
irrelevant

### Web Browser and Version
irrelevant

### Hugo Version
Unknown

I think this should be able to be fixed by adding a `url` parameter to the `share` URL which specifies the URL of the episode page.

**Comment by alexmurray** [comment]
Ah I see this is because for episode pages "permalink" is not defined by default - so manually specifying this for an episode results in the Right Thing™ but as you can see from the demo site this does not happen by default so perhaps this should be generated by default OR something else should be used.

**Comment by mattstratton** [comment]
Aha! I think that the fix will be to change this:

```
     {
        share: "twitter",           // name of share
        label: "Tweet",             // share button text (optional)
        logo: "fab fa-twitter",
        {{ if (isset .Site.Params.social "twitter" )}}
          via: "{{ .Site.Params.social.twitter }}",       // custom twitter sharing param 'via' (optional)
        {{ end }}
        url: "{{ .Params.permalink }}",
        text: "{{ title .Title }}"
      },
```

to:

```
     {
        share: "twitter",           // name of share
        label: "Tweet",             // share button text (optional)
        logo: "fab fa-twitter",
        {{ if (isset .Site.Params.social "twitter" )}}
          via: "{{ .Site.Params.social.twitter }}",       // custom twitter sharing param 'via' (optional)
        {{ end }}
        url: "{{ .Permalink }}",
        text: "{{ title .Title }}"
      },
```

That will make it use the built-in value of `Permalink`, not try to use the one set in frontmatter.

Let me test this and if it fixes it, I'll push a fix.

**Comment by mattstratton** [comment]
Released the fix for this in https://github.com/mattstratton/castanet/releases/tag/1.1.24
