### ISSUE TITLE
guid episode tag should be unique and not change

### ISSUE THREAD

**Issue by alexmurray** [mattstratton/castanet#209]
As per https://itunespartner.apple.com/en/podcasts/faq/Updating%20your%20show_Basics the guid should be a unique id, not a URL etc which might change. An easy way to allow this and to not break existing deployments would be to allow this to be specified as an attribute.

### Expected behavior
guid is unique and independent of media URL and can be specified manually.

### Actual behavior
guid is the URL of the media file.

### Reproduction Steps
N/A
### Operating System and Version
N/A
### Web Browser and Version
N/A
### Hugo Version
N/A

**Comment by mattstratton** [comment]
Fixed in #210
