### ISSUE TITLE
[Bug] Can't navigate guest listing on mobile

### ISSUE THREAD

**Issue by robwirving** [mattstratton/castanet#217]
Noticed this issue both on my site and on arresteddevops.com

If you go to a castanet themed website on mobile and click on the Guests link then scroll to the bottom there will be 3 buttons available to navigate the listing. The "<< <<" button to go to the first page, the "<<" button to go to the previous page (which isn't clickable since you're on the first page) and the ">> >>" button to go to the end of the results. 

There is no way to go from the first page to the 2nd page (unless you only have 2 pages). Instead the only way to navigate the guest list on mobile is to skip to the end of the results, then traverse through the pages backwards.

The episode listing pages seem to handle this better

**Comment by mattstratton** [comment]
Well that's not great!

I'm going to have to dig into the pagination code to fix #219, so I'll look at this at the same time.

**Comment by mattstratton** [comment]
Fixed in #221
