### ISSUE TITLE
Theme does not work on Hugo 0.58

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#219]
This is a pretty big issue, but I'm aware of it. The homepage will not load episodes if you are using Hugo 0.58 or higher. I expect to resolve this issue within the next few weeks.

**Comment by Fweeb** [comment]
Any progress on this? I know it's selfish of me to ask, but I was thinking I'd resurrect a podcast built on this theme, but it's proven difficult to post a new episode. :)

**Comment by mattstratton** [comment]
Sorry that I've been delaying on this! I got stuck with a bunch of work travel. I'm going to dig into this tonight and hopefully knock it out!

**Comment by mattstratton** [comment]
The good news is, the fix was super easy (once I was looking at the right code).

The less good news (well it's not bad, just a thing to watch out for) is that you have to add a setting to your config file now for the theme to work at all. It's documented in the REFERENCE.md file (once I merge the PR and do the release, etc)

**Comment by mattstratton** [comment]
@Fweeb - go ahead and download v1.0.1 from the Releases page; this should work for you now!
