### ISSUE TITLE
[Bug] Image Doesn't Show up on Page 2 of Episodes in List View

### ISSUE THREAD

**Issue by mary-grace** [mattstratton/castanet#231]
### Expected behavior
On Page 2 of episodes, the associated banner image doesn't show up. 

### Actual behavior
Instead, it renders as a broken box. This happens whether there's an image associated with the episode or not.

[screenshot](https://www.dropbox.com/s/w05o88ebu5699uc/Screenshot%202019-11-16%2016.08.20.png?dl=0)

### Reproduction Steps
Click through on Page 2 of episodes on Community Pulse: http://communitypulse.io/page/2/

### Operating System and Version
macOS Mojave, 10.14.6

### Web Browser and Version
Chrome, Version 78.0.3904.87

### Hugo Version
I'm personally running 0.36 (I know I need to update) but this is happening no matter who's submitting the PRs, including the latest versions of Hugo.

**Comment by mattstratton** [comment]
Well this doesn't sound great :)

I look into this today!

**Comment by mattstratton** [comment]
(adding a clarifying note to myself - this happens on all pages after the first page, not just page 2)
