### ISSUE TITLE
[ENHANCEMENT] Add episode tags support.

### ISSUE THREAD

**Issue by javierinsitu** [mattstratton/castanet#245]
Tags are very useful mainly in large audio episodes.

**Comment by mattstratton** [comment]
Great - can you provide a little more info on these tags? What is the xml they use? is it an `itunes` feed tag, and if so, what is the tag? I'm happy to add this, just need to know what the output should look like (I assume these tags would be generated from frontmatter in an episode?)

**Comment by mattstratton** [comment]
@javierinsitu - can you let me know what tags you're looking for, specifically what it looks like in the final feed? Or do you mean Hugo tags?

**Comment by javierinsitu** [comment]
Hello. Sorry for the delay.
I am referring specifically to Hugo tags. An unsophisticated spec, I thing.
