### ISSUE TITLE
[Bug] "orange", "blue" theme menus don't expand on wide screen like grey theme

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#252]
### Expected behavior
I started a fresh hugo install and castanet exampleSite. With "grey" theme configured the header menu expands when I widen my browser window. Same should be true with "orange", "blue" themes.

### Actual behavior
When I make it narrow it collapses into a hamburger menu. With "orange", "blue" themes the menu doesn't expand.

It looks like it "grey" theme is using bootstrap v4.3x and orange & blue are v4.0x. Maybe that's the cause of the difference.

### Reproduction Steps
Start a fresh hugo install and castanet exampleSite site, observe the header menu when config set to "grey" versus "orange" or "blue" theme.

### Web Browser and Version
Chrome

**Comment by mattstratton** [comment]
Ooh. that's weird that when I did the updates recently it didn't compile new versions of the orange and blue ... the gulp task is supposed to do that. I'll look into that in the next few days.

**Comment by mattstratton** [comment]
Note that while I have merged this fix into master, it's not been released yet (so if you're pulling from https://github.com/mattstratton/castanet/releases you won't get it yet, but if you're using the theme as a submodule you will)

**Comment by mattstratton** [comment]
strike that - I just pushed 1.2.3 which includes this fix.

**Comment by rajeshduggal** [comment]
@mattstratton the fix works for us! Thanks!

**Comment by mattstratton** [comment]
Oh good!!
