### ISSUE TITLE
gulp task doesn't compile orange and blue files

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#254]
Looking at https://github.com/mattstratton/castanet/blob/master/gulp/tasks/dev/sass.js

I think the problem is all the tasks are named `sass`, so gulp probably only runs the last one.

**Comment by mattstratton** [comment]
This should take care of #252

**Comment by rajeshduggal** [comment]
@mattstratton is this something you might be able to troubleshoot and fix pretty quickly when you get time? Or would it be worthwhile for me to start looking into how this works and start working on this too when I get some time? Cheers.

**Comment by mattstratton** [comment]
@rajeshduggal I'll work on it this weekend!
