### ISSUE TITLE
[Bug] /host/ page not displaying each host's main content

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#266]
## Expected behavior
Hosts page ( http://localhost:1313/host/ ) should show the main markdown content from each host's markdown file.
In file "castanet/layouts/partials/hosts.html", changing this line:
<p>{{ .Content | markdownify }}</p>
To this..
<p>{{ .Content }}</p>	
Seems to fix it for me.

### Actual behavior
Host's images are included but the main markdown content isn't displayed ln the hosts page.
http://localhost:1313/host/

### Operating System and Version
Ubuntu

### Web Browser and Version
Chrome

### Hugo Version
0.68.3

**Comment by mattstratton** [comment]
This was fixed in [1.2.0](https://github.com/mattstratton/castanet/releases/tag/1.2.0)

**Comment by mattstratton** [comment]
oh wait, that was for guest pages... I'll fix this right away.

**Comment by mattstratton** [comment]
This was merged into master and released with [1.3.2](https://github.com/mattstratton/castanet/releases/tag/1.3.2)

Thanks for catching it!
