### ISSUE TITLE
[ENHANCEMENT] - Add support for preferred pronouns for guest and host

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#274]
Should add a field in both guest and host frontmatter for preferred pronouns, and display them if they are added

**Comment by mary-grace** [comment]
🤔 Maybe this is only new for the hosts? It already appears for me in the `guest` frontmatter.

**Comment by mattstratton** [comment]
Yeah, either way, it doesn't get used anywhere though :)

I mean, you can put them in the frontmatter, but they aren't displayed anywhere.

The fact that they are populated in the archetype is what made me realize that I needed to actually *do* something with them.

**Comment by darinpope** [comment]
which field in `guest` is being used for pronouns? I'm not seeing it.

**Comment by mattstratton** [comment]
None - this isn't a feature yet. Need to add the field (and add to archetype) and then do some kind of display

**Comment by mattstratton** [comment]
I don't know how @mary-grace was getting it though 😂

**Comment by chrisreddington** [comment]
@mattstratton - I've taken an attempt at this one in the above PR :)
