### ISSUE TITLE
add host support to episode page

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#28]
To clarify, this will work similar to guests. If a host(s) is set for the episode, they should display in a set along with the guests.

**Comment by mattstratton** [comment]
This needs some thinking, as it is subject to the retcon problem.

**Comment by mattstratton** [comment]
My idea here is that under the guests, it also lists (in similar style, and only if set in the frontmatter), the hosts for that episode). I think that it's especially important that a "host" style page gets created for each host, rather than pulling it from the `config.toml` due to retcon.

The "About" page for the hosts should always reflect most current, though.

@bridgetkromhout? Your thoughts?

**Comment by bridgetkromhout** [comment]
Fine by me! Is the main goal to allow people to find the eps that feature, say, Trevor? Do we then also want a host's eps to be listed on their personal page, like with a guest?

**Comment by mattstratton** [comment]
for this one, it's both. Currently, there is an "About" page, which is driven by the content of `config.toml`, which will always be "up to date" 

(provided the host keeps it up to date; Trevor's bio in config.toml still says that he works at 10th Magnitude).

The main reason I wanted to include the hosts feature to an episode page is so that on a particular episode, it would list the hosts that participated, as well as the guests. So in my theory, it's less about being able to find a guest, etc.

I'm thinking the solution is that you end up with a set of pages under `content/hosts` for each host, which allows for a host's own "homepage", as per guests. The content of this file is what provides the bio for the episode page.

I don't think you ever end up having a `/hosts` url that lists all of the episodes that host took part in..although you could. I would create the list template for that just like we did for guests, and if the podcast owner decided they want that, they could use it.
