### ISSUE TITLE
Remove unnecessary files from release archive

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#303]
A bunch of stuff isn't being excluded from the release artifact. 

One example is the `images` directory which only is needed for the repo, I think. 

I sorta think the `gulp` directory can be excluded too, since I don't think there's a use for running `gulp` inside the theme directory when someone is using the theme, but I could be wrong.

**Comment by rastacalavera** [comment]
I deleted the gulp folder, images folder and gulp.js from the latest theme and my site built fine so i think it is safe to exclude from the release.
