### ISSUE TITLE
[ENHANCEMENT] - Add taxonomies for Tags, Series and Categories

### ISSUE THREAD

**Issue by chrisreddington** [mattstratton/castanet#306]
I've been working on enhancing my own deployment of the site to leverage Hugo Taxonomies for Tags, Series and Categories.

You can find a live version at https://www.cloudwithchris.com/

I merged this into my master branch at https://github.com/chrisreddington/cloudwithchris.com/commit/68191a6518fa716ba7539aa33d362cb5043299e7 

Would you approve of these changes to be merged into the castanet theme, and if so, any additional requirements? I'm mainly thinking around configuration of whether folks would want tags/categories/etc. on their own pages, so making sure there is some flexibility (which I hadn't yet considered in my deployment).

Thanks!

**Comment by mattstratton** [comment]
Let me take a look! I think the biggest thing is to ensure that it doesn't break if someone doesn't use tags/series/categories...I'll dig into that.

the biggest requirement I could see beyond that is making sure that we update REFERENCE.md with documentation on how to use them, etc.

**Comment by mattstratton** [comment]
I found a bug in your `partials/row.html` where it looks like it's selecting only upcoming; that would need to be fixed.

also, the taxonomy pages are not filtering based on `upcoming`, which I think would need to be fixed?

**Comment by mattstratton** [comment]
Let's put it this way - can you put together a PR with these changes? It might be easier for me to review that way, since it would only include the changes for the theme.

also, you'll want to add each type of taxonomy to some of the episodes in the `exampleSite` (as well as the config for `exampleSite` so we can see how it works!

**Comment by chrisreddington** [comment]
Absolutely, will get to that later today/tomorrow. Just wanted to first figure out if this was useful to bring the changes back into the repo before putting the effort there :)

**Comment by mattstratton** [comment]
Definitely useful! I feel like there might even be an existing issue on this...let me find it!

**Comment by mattstratton** [comment]
I suspect this would handle #245
