### ISSUE TITLE
[BUG] - Row layout uses a different media player than episode pages

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#320]
I don't know how/when this happened, but it's weird.

in `partials/row.html`:

```
<audio src="{{ $.Site.Params.media_prefix }}{{ . }}" preload="auto" />
```

in `episode/single.html`

```
          <audio id="player2" style="width: 100%" controls preload="none">
            <source src="{{ $.Site.Params.media_prefix }}{{ . }}" type="audio/mp3">
            </audio>
```

**Comment by mattstratton** [comment]
okay so in #242 I only updated the episode page and not the row layout. So the `episode/single.html` is likely the right one to use.

**Comment by chrisreddington** [comment]
This may also relate to my coment in #325 about adding flexibility on which player to use. I wonder if it might be worth a wider look at using partials for players, and having some kind of site-config to switch out which player is used?

**Comment by mattstratton** [comment]
I think that what might be a better DRY move is to create a partial that is basically "show the player", which we can use in both the episode template and the row template; even though that partial is pretty small, it should work. Might be a little tricky to make sure we pass the audio file name properly to the partial but it's not that tough.
