### ISSUE TITLE
[BUG] - <itunes:explicit> tag should be true/false not yes/no

### ISSUE THREAD

**Issue by rajeshduggal** [mattstratton/castanet#326]
The google documentation says that the `<itunes:explicit>` tag values can be "yes" or "no".
https://support.google.com/podcast-publishers/answer/9889544

But! The apple documentation says that this tag, which can be set on the feed, and/or on individual items, should be "true" or "false", not yes/no!

https://help.apple.com/itc/podcasts_connect/#/itcb54353390
https://itunespartner.apple.com/podcasts/articles/validate-your-podcast-3064

Some rss validators will flag `<itunes:explicit>`  yes/no values as invalid.

These castanet files (maybe there are others) should be updated to use apple's documented true/false rather than yes/no:
- https://raw.githubusercontent.com/mattstratton/castanet/master/archetypes/episode.md
- https://github.com/mattstratton/castanet/tree/master/exampleSite/content/episode/*md
- https://github.com/mattstratton/castanet/blob/master/REFERENCE.md

**Comment by chrisreddington** [comment]
So it wouldn't be as simple as just changing all items to yes/no in those files. I think we'd have to change how the RSS Feed is generated, as Google Play uses yes/no [Ref here](https://support.google.com/podcast-publishers/answer/9889544?visit_id=637434583532245381-414346112&hl=en&rd=1).

I can take a look at this one @mattstratton

**Comment by mattstratton** [comment]
PR #327 looks like it's almost the right fix; I made a few comments on how to handle this a little better in that PR.
