### ISSUE TITLE
[BUG] - Remove blog from jumbotron when not in use

### ISSUE THREAD

**Issue by lnxchk** [mattstratton/castanet#338]
**Describe the bug**
We aren't going to use the blog feature, but there's no way in the config to not have "Blog" show up in the jumbotron div.

**To Reproduce**
1. Working on upgrading Page it to the Limit site to 1.14.1 
2. Added no additional settings to config.toml for the blog feature
3. Blog shows up in jumbotron and results in a 404

**Expected behavior**

If the blog section isn't initialized in config.toml, there should be no mention of a blog on the site.

**Screenshots**
![Screen Shot 2021-02-16 at 6 20 28 PM](https://user-images.githubusercontent.com/588600/108134456-4032d800-7084-11eb-9732-16fbea2b8fb4.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: chrome and firefox
 - Hugo version v0.74.3

**Additional context**
I copied some code out of head_includes.html to suppress the blog button, and that seems to work. I don't know if that is the best way to do it though.

I added 
{{ if eq .Section "blog" }}
at line 75 and an end at line 81

**Comment by mattstratton** [comment]
oh snap. This should be fixed soon. Sorry!

**Comment by mattstratton** [comment]
I am pushing up a PR now to fix this; had to do something a little different but I think it works!

**Comment by mattstratton** [comment]
There'll be a fix released in the next 10 min or so!
