### ISSUE TITLE
[ENHANCEMENT] - some tool that helps with uploads to all used services

### ISSUE THREAD

**Issue by supersexy** [mattstratton/castanet#341]
Does exist some tool that could help with distribution of the actual audio file to all services that you are using here with this theme?
I know, that is maybe a bit out of scope of a Hugo theme, but it may make sense to have such a thing hooked up to make the publishing more automated? Any ideas, hints? Thanks!

**Comment by mattstratton** [comment]
There is! I personally use [Auphonic](https://auphonic.com/) to process our audio, and it then can upload to various services!

**Comment by supersexy** [comment]
Interesting! Do you use their API? Do you integrate this in any way with a Hugo deploy or is it wise to keep that a separate process?

**Comment by mattstratton** [comment]
Oh, were you talking about distribution to services like Spotify, etc? I was thinking of hosting services like Blubrry, etc. 

For most of the services, once they have your feed, they will auto-update themselves when you post new episodes; getting into those services is almost always a slightly manual process (for Spotify, I have gotten shows in there via the fact that I host with Blubrry and that's part of it)

**Comment by supersexy** [comment]
I would like to automate the whole process as much as possible.
I found podlove with ultraschall very interesting. Auphonic also looks very good.

This theme is very nice for a minimal setup and static sites - with some more love for smart automation of the submit / upload part it could be a nice setup. I will play around with it and see, if it fits my process.

Thank you very much for your hints!

**Comment by rastacalavera** [comment]
I have been experimenting with [podcast generator](https://podcastgenerator.net) for my rss which snaps into itunes and the others. You could write a shell script that executes on a folder to sftp the file to the PG instance and just keep the shell script living in your project folder and maybe use cron to run it. I made a shell script that will automatically resize images using ffmpeg depending on the criteria of icon/host/episode/ etc that I just keep in my project folder for easy access.

**Comment by ctindel** [comment]
@mattstratton This seems out of scope for this project.  

People who want a service that makes it easy to publish to all the different players could use anchor for free or any of the other paid projects I think.

**Comment by mattstratton** [comment]
I agree - this isn't really as much an issue as it is an overall question
