### ISSUE TITLE
Where should the mp3 be stored?

### ISSUE THREAD

**Issue by rastacalavera** [mattstratton/castanet#344]
Getting close to pushing out an episode! I just don't know where to put the mp3 file. I currently have it the episode folder and I am guessing that is the wrong location. In the episode header the is `podcast_file=[]` and i've tried putting in ["content/episode/E00/E00.mp3"] and ["E00.mp3"] but neither seems to work.

**Comment by rastacalavera** [comment]
I think I just had an “aha” moment. In the toml for media prefix, would I put the url to my gitlab page where the mp3 is stored? If that’s true, would l have to keep all episodes in a single folder rather than having a separate folder for each one? For example ‘media_prefix = www.ABC.com/content/episode/EEO/‘ or ‘ www.ABC.com/content/episode/’ ? I get the feeling all episodes HAVE to be in a single folder. My computer died on my so I’m taking that as a sign it’s time to call it and night and revisit this later in the weekend.

**Comment by cbrake** [comment]
for my [podcast](https://tmpdir.org), I store podcast files on google cloud. Example:

https://storage.googleapis.com/tmpdir-podcast/008.mp3

and then in `config.toml`, I have:

`media_prefix = "https://storage.googleapis.com/tmpdir-podcast/" `

I like keeping the podcast files separate from the actual site as it simplifies deployment a little -- I don't have store the podcast files in git, or come up with a way to sync them, etc.

**Comment by rastacalavera** [comment]
That makes sense. I’ll see if I can get it to work with gitlab then as it grows, change to something else like google cloud or a digital ocean/linode server.
