### ISSUE TITLE
[ENHANCEMENT] - Hyperlink default color

### ISSUE THREAD

**Issue by rastacalavera** [mattstratton/castanet#347]
**Describe the solution you'd like**
Is it possible to have a hyperlink show up as blue or some other color? Right now it's an off gray which makes it hard to stand out from the default text color.
An example of this can be seen in my latest [episode](https://linuxlemming.com/e04/) where the word `blog` is the hyperlink.
I tried some googling and I know it's a theme setting and I assumed it would be in the `layout/partials` area but can't really find anything obvious.

**Comment by mattstratton** [comment]
You can override any of the CSS classes by setting the `custom_css` value in your `config.toml` file. This is documented (not super clear, I realize) in [REFERENCE.md](https://github.com/mattstratton/castanet/blob/main/REFERENCE.md) under [General Parameters](https://github.com/mattstratton/castanet/blob/main/REFERENCE.md#general-parameters)


>Array of custom CSS files for over-riding theme settings or adding your own classes. These files should be put into your static directory (not the static directory of the theme).

You can set it looking something like this: `["my_custom.css", "other_custom.css"]`

**Comment by rastacalavera** [comment]
Interesting. So in my toml i put in `custom_css= lemming.css` and created a file, `lemming.css` in the static folder of the project (not the theme) and when I launch the local server I got this error
```
Change of config file detected, rebuilding site.
2021-04-06 13:24:18.088 -0500
ERROR 2021/04/06 13:24:18 render of "page" failed: execute of template failed: template: _default/single.html:4:3: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:12:3: executing "partials/head.html" at <partial "head_includes.html" .>: error calling partial: "/home/rastacalavera/git/ll-dev/linuxlemming/themes/castanet/layouts/partials/head_includes.html:34:14": execute of template failed: template: partials/head_includes.html:34:14: executing "partials/head_includes.html" at <.Site.Params.custom_css>: range can't iterate over custom.css
```
I might try a fresh deploy and see if the same error occurs.

**Comment by mattstratton** [comment]
you need to specify it as an array, so it should be like this:

```
custom_css = ["lemming.css"]
```
