### ISSUE TITLE
[BUG] - When site theme is blue, rolling over the social icons doesn't highlight them

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#349]
**Describe the bug**
Put the site in blue mode, then hover with your most over the header social media icons.  Or maybe it does but the blue is so similar you can't tell whereas it really pops for example in the orange. 

**To Reproduce**

**Expected behavior**
The highlight color should be different enough from the base icon color so you can tell when you're rolling over it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. OS X, Windows, Linux]
 - Hugo version

**Additional context**

**Comment by mattstratton** [comment]
I'll take a look and see what colors to switch to for that to be more apparent.

**Comment by ctindel** [comment]
Well when you have the orange icons switch to blue in the orange them it looks good, maybe the blue icons could switch to orange when hovering in the blue theme?
