### ISSUE TITLE
[ENHANCEMENT] - Add support for embedding anchor.fm player

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#352]
**Is your feature request related to a problem? Please describe.**
Can you add support in the episode files for embedding a link to an anchor.fm player?  

**Describe the solution you'd like**
A configuration option in the episode markdown files that would embed the anchor player both on the episode detail page and right on the home page.  See their twitter thread for details:

https://twitter.com/anchor/status/992119358510989314?lang=en

I'd be happy to test this out for you if you don't have an anchor.fm podcast to test with.  Or I can give you my embed code to test with as well.

Probably other sites have similar functionality but since anchor.fm is the best free hosting service it probably makes sense to start with them anyway.

**Comment by mattstratton** [comment]
I'm a little leery about adding more players; it's not something that I can regression test, but I think what might work is to have the ability to disable the built-in player and support adding a custom embed. I'll have to think about how that works; you would have to copy-paste the embed per episode each time somehow but there might be a way to make that slightly not cumbersome.

**Comment by ctindel** [comment]
Yeah the way anchor works is that they only give you a per-episode embed link so it would be done in the episode markdown.

TBH I'm not sure how this would be any different than the youtube link which is also done per-episode.

I think an option to embed custom player html would be a decent solution as it would theoretically work for any player.

**Comment by mattstratton** [comment]
well, the thing is for youtube you pass in the URL of the video, but the theme does things with it for the layout, etc. 

I think for this to work it would have to be "option to disable built in player" and you'd have to put the embed code into the markdown file? It would also remove the player working on the list of episodes, etc.

**Comment by ctindel** [comment]
Couldn't the list of episodes also show the embedded player?

**Comment by mattstratton** [comment]
Not really, since it's specifically styled to show up and since I don't know what an iframe would look like (no idea what comes in the iframe) it could push things all over the place :)

**Comment by mattstratton** [comment]
I definitely want to create as much flexibility for use with this theme, but heavy customizations are tricky since it has to work for...everyone :)

Let me spend some time thinking about a way to work out an alternative for different embedded players.

**Comment by ctindel** [comment]
Yeah I understand.  But I would say that since anchor.fm is the most popular totally free hosting solution for podcasts, and it is owned by spotify, it seems worthwhile to elevate that to a level that the theme provides a custom option for (and formats properly).

In my mind this is no different than the theme explicitly providing support for an embedded youtube video, which is also a popular and totally free way of distributing media.

**Comment by ctindel** [comment]
Closing this for now, I see it would be very complicated.
