### ISSUE TITLE
[BUG] - Can you change the link to the podcast rss to say "RSS Feed" instead of "Podcast"?

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#355]
**Describe the bug**

I know the icon is for an RSS feed its just that every one of those links is to a "podcast" so it would be nice for perhaps non-savvy users whose apps are telling them "Put the RSS feed here" to explicitly call out in the button text that it is the RSS feed by having the button say "RSS feed" or "Podcast RSS" or something similar.

**Comment by mattstratton** [comment]
I think you're right that "Podcast RSS" and "Blog RSS" is better.
