### ISSUE TITLE
[BUG] - Episode icon isn't centered

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#357]
**Describe the bug**

You did fix the problem where the episode description text wasn't aligned with other episodes, but also the icon is not centered in the place where it is.  See this attached screenshot to get an idea.

At a minimum I think the description text should be centered with respect to the show icon and not have quite so much white space between the icon and the text.

<img width="906" alt="Screen Shot 2021-04-07 at 6 33 35 PM" src="https://user-images.githubusercontent.com/1863749/113943221-35690980-97d0-11eb-92d8-f93e0368ba68.png">

I don't know the right way to fix it, it just doesn't seem to look great the way it is right now.

**Comment by mattstratton** [comment]
I think that the issue is your images are too small; the design is based around having larger thumbnails (since you need those for grid layout, so it has to be able to handle both)

![image](https://user-images.githubusercontent.com/1280666/113946192-6dbb1880-97cd-11eb-8c2c-8d8e9e37080f.png)

I should provide some minimum sizes in the docs for those images for the best experience though!

**Comment by ctindel** [comment]
Well, it's supposed to be a thumbnail right not some huge image.  Personally I'd like to see a minimalist option that fits more episodes on the page at once.  I mean look at how much whitespace there is on your screenshot.

If the issue is that grid layout needs bigger images, then maybe let people supply both row and grid images and use smaller images for the rows and bigger images for the grids?  i.e. episode0-row.png, episode0-grid.png, and failback to episode0.png if the row and grid options aren't there.  

Or just tell people what size image to use for grid and what (smaller) size image to use for rows.

Or, have a compact row option that's separate from the current row option (for backwards compatibility)?

Lots of options.

**Comment by mattstratton** [comment]
Let me try it with moving the thumbnail over; right now I think it's `col-md-4` and if we make it `col-md-3` it will take up less room for sure.

**Comment by mattstratton** [comment]
#358 changes the layout a bit and removes some of the extra padding around the images and description. After the deploy preview is done building, I'll put in a link here to review.

**Comment by mattstratton** [comment]
OK, so you can see it here https://deploy-preview-358--sample-castanet.netlify.app/

Again, the thumbnails are larger than yours, so it won't look exactly the same, but it takes up 3 columns instead of 4, and I removed some of the padding around them.
