### ISSUE TITLE
Missing navbar items when testing included example site

### ISSUE THREAD

**Issue by thercast** [mattstratton/castanet#36]
Hello, first I'm a fan of Arrested Devops and thank you for creating this theme!  I'm a fellow podcaster and currently I'm using the [Nikola](https://getnikola.com/) static-site generator but would like to migrate over to Hugo due to a variety of reasons.  You can see my podcast page at [r-podcast.org](https://r-podcast.org/).  I installed Hugo on both my laptop (running arch linux via the snap hugo package) as well as on a digital ocean VPS running ubuntu 16.04, and to test out your theme I created a new site, downloaded castanet within the `theme` subdirectory like usual, and copied over the contents of the `exampleSite` directory to the test site.  The only part I changed was the `baseUrl` directive in `config.toml`.  When I serve the site locally using `hugo server` and view the site at `localhost:1313`, I see most of the site renders exactly as your example at <http://sample-castanet.netlify.com/> but my version is totally missing the `About`, `Contacts`, and `Resources` items in the navigation bar (see screenshot below).  I'm new to Hugo so it's quite possible I'm missing a step or two, but can you help me to at least render your example site exactly as yours renders?  I don't feel comfortable making the tweaks to the site for matching my podcast until I can at least start from a working state!  Let me know if you would like additional information.

![hugo_local](https://cloud.githubusercontent.com/assets/1043111/22191470/f36f4eb4-e0f8-11e6-8274-f88cca7a2b4c.png)

**Comment by mattstratton** [comment]
I suspect this is something that broke in the later hugo; even given the code and config that is on the sample site, when I build it locally, the menus disappear. I'm going to see if I can puzzle this out.

**Comment by thercast** [comment]
Thanks for looking in to this!  Happy to help test further or provide additional info if needed.

**Comment by thercast** [comment]
Just a quick check on any updates?  FWIW I experimented with compiling your arresteddevops site files locally and the navbar elements appeared without a problem.   But it looks like you use a more custom theme for it.

**Comment by thercast** [comment]
After consulting the Hugo [template debugging docs](https://gohugo.io/templates/debugging/) combined with a reported [URL issue](https://github.com/spf13/hugo/issues/2770) I believe I've found the solution.  It turns out that you need to specify `.Site.Menus.main` as opposed to `.Site.Menus.Main` within the [layouts/partials/header.html](https://github.com/mattstratton/castanet/blob/master/layouts/partials/header.html#L19) file.  After making that small change I can now see the correct menu items!  I'll submit a PR shortly.
