### ISSUE TITLE
[BUG] - Update config.toml and sample site to add trailing / for the URLs

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#361]
**Describe the bug**
Some hosting sites like AWS/S3/Cloudfront have trouble with pretty URLs that have no trailing / for a url that refers to a directory.  That's why the hugo creators decided it would be the "correct" way to do things in hugo way back when:

https://github.com/gohugoio/hugo/issues/492#issuecomment-54968263

**Comment by mattstratton** [comment]
Yeah, I was saying why not PR in the change yourself? It's just a small change to one file (I can do it myself too, but saying that PRs are always welcome!)
