### ISSUE TITLE
[ENHANCEMENT] - Can we make an option to have youtube be a link on the main page just like spotify et al?

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#364]
**Is your feature request related to a problem? Please describe.**
I know that the "socials" part up along the top bar includes a youtube option because that makes sense for non-podcast type websites.  But for video podcasts where youtube is really a primary distribution platform alongside spotify and apple music, it seems strange not to have a big link to it next to those others.

**Describe the solution you'd like**
Would be great to have the ability to specify a youtube_subscribe link alongside the others for people who also publish their podcast episodes straight to youtube so the channel link is as prominent as the audio-only services.

**Comment by mattstratton** [comment]
Fixed in #368
