### ISSUE TITLE
[BUG] - Trouble using theme as a hugo module

### ISSUE THREAD

**Issue by ctindel** [mattstratton/castanet#382]
So I was having trouble with amplify not pulling the latest version of the theme after you merged all those PRs.  I have no idea what the problem is, but it seems like the new hotness is to use themes as submodules like here:

https://discourse.gohugo.io/t/how-to-add-a-theme-using-modules-for-beginners/20665

But when I tell hugo to pull the theme it seems to pull some really old version?

```
root@773a6171b6b6:/mnt/sib# hugo mod get -u
hugo: downloading modules …
go: downloading github.com/mattstratton/castanet v0.5.1
go get: added github.com/mattstratton/castanet v0.5.1
```

I'm not really sure what's going on.  Does it mean that your CICD needs to push it as a hugo theme every time you bump the version or something?

**Comment by mattstratton** [comment]
Sorry for the MASSIVE delay on this (i'm sure it doesn't help you now) but I finally figured out the issue - hugo mod requires the releases to be tagged as "vx.x.x" not "x.x.x" so it was pulling v0.5.1 since that was the most recent version that actually...had a v tag
