### ISSUE TITLE
[BUG] - audio buttons not showing up

### ISSUE THREAD

**Issue by nicole-brewer** [mattstratton/castanet#384]
I appear to have the same issue as #362, but for different reasons. The play button is clickable, but the symbol is missing and does not play audio. The volume icon is also missing. I will start by addressing the questions you asked the other user with a similar issue.

> Do you see the button on this site? It's built when merged from `main` <br><br>https://sample-castanet.netlify.app/

Yes, I do see the button on that site. 

> If you switch to the blue theme do you have the same issue? I can try building on my computer later to see if grey isn't working (I'm fairly certain I tested it on grey but not sure) but that would be later tonight.

I switched from grey to blue and I still have the issue.

> For the record, this is how I "upgrade" the theme
(snippet of bash - [full script](https://github.com/mattstratton/quiche-anon/blob/main/utils/update-theme.sh) for reference) <br><br>wget https://github.com/mattstratton/castanet/releases/download/$version/castanet-$version.zip
rm -rf themes/castanet
unzip castanet-$version.zip -d themes/

I followed these instructions and updated my theme to the latest release which is 1.17.1

Despite all this, both locally and when deployed, I don't see the play buttons. I wonder if you have any ideas about what's going on. Here you can see the [most recent deployment](https://nicole-brewer.github.io/long-tales-of-science/). 

Any insight appreciated! Thanks

**Desktop:**
 - OS: OS X
 - Browser: Firefox
 - Hugo version: ‘0.92.2’

**Comment by nicole-brewer** [comment]
Okay. If I inspect my site served locally, I get an 404 not found error in response to the following request: 

<html><head></head><body><span class="message-body-wrapper">

GET | http://localhost:4321/img/mejs-controls.svg
-- | --

But the file is where it should be in themes/castanet/static/img/mejs-controls.svg

**Comment by mattstratton** [comment]
I apologize that I'm just seeing this now! I'll try to take a look tomorrow and see if I can figure out anything that looks squirrelly.

**Comment by mattstratton** [comment]
I noticed in your config file for Hugo that your baseUrl does not end in a "/"...That can cause some issues with this theme (to be honest I don't know if this is one of them, but it might affect how some assets get loaded?)

**Comment by mattstratton** [comment]
Closing this issue. Please re-open it if needed.
