### ISSUE TITLE
[ENHANCEMENT] - Add Mastodon to the Social options

### ISSUE THREAD

**Issue by rastacalavera** [mattstratton/castanet#392]
**Is your feature request related to a problem? Please describe.**
Since Mastodon is kind of taking off while Twitter implodes, it might be a great time to add that option to the theme.

**Describe the solution you'd like**
The fa-brands have it included already so it is just a matter of turning it on as an option in the main config `.toml` and in the guest/host single and list pages. The guest/host archetype front matter would have to reflect this as well.

**Hang ups**
Since the service isn't centralized, it would be ideal to add a way so that it doesn't require a prefix and the user would just use a fully qualified url to their account. I am not sure how best to do this, when I played with it and tried to remove the prefix stuff, it crashed the whole thing.

**Comment by mattstratton** [comment]
Very reasonable! I'll try to get this done this week.
