### ISSUE TITLE
[ENHANCEMENT] - add support for Threads

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#411]
Add social options for hosts, guests, and shows for:

- Threads
- Bluesky

(note: i don't know if fontawesome has icons for those though)

**Comment by mattstratton** [comment]
okay threads should work maybe? although that is labeled as only in version 6 and above hmm

<i class="fa-brands fa-threads"></i>

**Comment by mattstratton** [comment]
update - for now this issue is only for Threads, as Bluesky doesn't have anything decent in FontAwesome

**Comment by Mar-Koeh** [comment]
> Bluesky doesn't have anything decent in FontAwesome

@mattstratton that was correct at the time of writing. Three months later, in FontAwesome 6.5.2, they introduced [`bluesky`](https://fontawesome.com/icons/bluesky). In 6.7.1, they introduced [`square-bluesky`](https://fontawesome.com/icons/square-bluesky).
