### ISSUE TITLE
Doesn't work with one episode

### ISSUE THREAD

**Issue by lexi933** [mattstratton/castanet#44]
Trying to generate site with only one episode fails 

`ERROR 2017/04/12 17:02:55 Error while rendering "home": template: /home/alex/projects/advance-tech-podcast/themes/castanet/layouts/index.html:40:34: executing "main" at <after 1 (where .Data...>: error calling after: no items left`

**Comment by mattstratton** [comment]
Oh that's bad. I'll fix that!

**Comment by mattstratton** [comment]
Hmm. I'm not sure how this will work properly with only one episode, based upon the layout. I'm not sure what should display in the "episodes after the first one" would show up. It might look weird. Let me at least test the idea and see what it looks like.

**Comment by mattstratton** [comment]
OK, the fix is easy..fyi this is what it looks like when there is only one episode:

![](https://i.imgur.com/qOMLejJ.png)

**Comment by lexi933** [comment]
Hi Matt,
Thanks very much for your quick response :)

We've soft launched with a light version of your theme, if you want to check out our podcast you can find us here: https://advancetechmedia.org/

We're going to be partnering with other podcasts as we grow. If you'd like to be part of this let me know!

All the best!
Alexandra
