### ISSUE TITLE
Share your theme with the community

### ISSUE THREAD

**Issue by digitalcraftsman** [mattstratton/castanet#57]
Hi Matt,

all Hugo themes are usually listed in the [hugoThemes](https://github.com/spf13/hugoThemes/) repository and your podcast-based theme would be a great addition. Do you plan to add castanet as well?

Cheers,
Digitalcraftsman

**Comment by mattstratton** [comment]
It's on my todo list! I was waiting until I felt like it was share-able, but since folks are using it, it's time to share it :)

**Comment by mattstratton** [comment]
https://github.com/spf13/hugoThemes/issues/252 submitted!

**Comment by digitalcraftsman** [comment]
I'll close this issue since it draw enough attention for a submission. Thanks again Matt
