### ISSUE TITLE
[Bug] Site title and hamburger menu overlap in mobile view

### ISSUE THREAD

**Issue by thercast** [mattstratton/castanet#58]
I pulled up the [sample](http://sample-castanet.netlify.com/) castanet site on my LG G4 android phone (browser is chrome for android) and I saw that the site title __HugoCast__ and the "hamburger" icon (I'm sure there's a more technical name for this) were overlapping each other in the top center of the page view.  Here's a screenshot 

![screenshot_2017-04-27-01-26-27](https://cloud.githubusercontent.com/assets/1043111/25469245/25ab5e60-2ae9-11e7-818e-680eeca93bb5.png)

I'm fairly certain this only happened after your recent [update](https://github.com/mattstratton/castanet/issues/41) to bootstrap 4 because I viewed my podcast site [r-podcast.org](https://www.r-podcast.org) on my phone and the site title is left-justified while the hamburger menu is right-justified.  

Reproduction Steps: Load site in a small viewport

**Comment by mattstratton** [comment]
Oddly, this only seems to happen in Chrome with dev tools (I saw it there in the smaller viewport emulator) but not on mobile safari. I'll investigate it shortly. 

![img_4031](https://cloud.githubusercontent.com/assets/1280666/25482565/fe6662bc-2b17-11e7-908b-eca8d1f5cac2.PNG)

**Comment by mattstratton** [comment]
@thercast - ignore the aggressive bot :)

**Comment by mattstratton** [comment]
So I did find a workaround - the issue comes up when the nav contains a container, to make the navigation align with the middle container. When I remove that container, it makes the hamburger menu work fine.

I am thinking I'll commit this particular fix and open a new issue to get the navigation aligned properly.
