### ISSUE TITLE
Add support for banner-style images to episode page

### ISSUE THREAD

**Issue by mattstratton** [mattstratton/castanet#60]
In order for this to work for arrested devops, we need to support banner images on episode pages.

For example:

![](https://i.imgur.com/qbHYOJp.png)

My thought is to add an optional frontmatter to the episode, like this:

`episode_banner = "/img/episode/mybanner.jpg"`

If this is set, then the single episode template would display the banner across the top instead of the square image, and put the description below it.

**Comment by thercast** [comment]
I wonder if that would also be possible on the site home page too?  Not a huge deal but just something to consider.

**Comment by mattstratton** [comment]
@thercast that would definitely be a good addition, and I don't see why not.

Are you thinking that it would only be for the hero at the top, or for each episode?

The main reason I suspect I would rather have it only be for the hero, is because you might have some episodes with and some without, and it would look odd for the episodes that are the "same" (i.e., not the "latest") to look different from each other.

**Comment by thercast** [comment]
@mattstratton you are right.  I was thinking for only the hero at the top and I wouldn't want the inconsistency between the latest and non-latest episode views.
